---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: gomod
  pull: always
  image: golang:latest
  commands:
  - go mod vendor
  - git diff --exit-code
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-1.11
  pull: always
  image: golang:1.11
  commands:
  - make build
  - make test
  - make test-integration
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag
  depends_on:
  - gomod

- name: build-1.12
  pull: always
  image: golang:1.12
  commands:
  - make build
  - make test
  - make test-integration
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag
  depends_on:
  - gomod

- name: build-1.13
  pull: always
  image: golang:1.13
  commands:
  - make build
  - make test
  - make test-integration
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag
  depends_on:
  - gomod

- name: build-1.14-rc
  pull: always
  image: golang:1.14-rc
  commands:
  - make build
  - make test
  - make test-integration
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag
  depends_on:
  - build-1.11
  - build-1.12
  - build-1.13

- name: generate
  pull: always
  image: golang:latest
  commands:
  - make check-license
  - make generate
  - git diff --exit-code
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag
  depends_on:
  - build-1.13

...
