kind: pipeline
name: default
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - go mod vendor
  - git diff --exit-code
  environment:
    CGO_ENABLED: "0"
    GO111MODULE: "on"
  image: golang:latest
  name: gomod
  pull: always
  when:
    event:
      exclude:
      - tag
- commands:
  - make build
  - make test
  - make test-integration
  environment:
    CGO_ENABLED: "0"
    GO111MODULE: "on"
  image: golang:1.18
  name: build-1.18
  pull: always
  when:
    event:
      exclude:
      - tag
- commands:
  - make build
  - make test
  - make test-integration
  environment:
    CGO_ENABLED: "0"
    GO111MODULE: "on"
  image: golang:1.19
  name: build-1.19
  pull: always
  when:
    event:
      exclude:
      - tag
- commands:
  - make build
  - make test
  - make test-integration
  environment:
    CGO_ENABLED: "0"
    GO111MODULE: "on"
  image: golang:1.20
  name: build-1.20
  pull: always
  when:
    event:
      exclude:
      - tag
- commands:
  - make check-license
  - make generate
  - git diff --exit-code
  environment:
    CGO_ENABLED: "0"
    GO111MODULE: "on"
  image: golang:latest
  name: generate
  pull: always
  when:
    event:
      exclude:
      - tag
