kind: pipeline
name: default
platform:
  arch: amd64
  os: linux
steps:
  - commands:
      - go mod vendor
      - git diff --exit-code
    environment:
      CGO_ENABLED: '0'
      GO111MODULE: 'on'
    image: golang:latest
    name: gomod
    pull: always
    when:
      event:
        exclude:
          - tag
  - commands:
      - make build
      - make test
      - make test-integration
    environment:
      CGO_ENABLED: '0'
      GO111MODULE: 'on'
    image: golang:1.13
    name: build
    pull: always
    when:
      event:
        exclude:
          - tag
  - commands:
      - make build
      - make test
      - make test-integration
    environment:
      CGO_ENABLED: '0'
      GO111MODULE: 'on'
    image: golang:1.12
    name: build
    pull: always
    when:
      event:
        exclude:
          - tag
  - commands:
      - make build
      - make test
      - make test-integration
    environment:
      CGO_ENABLED: '0'
      GO111MODULE: 'on'
    image: golang:1.11
    name: build
    pull: always
    when:
      event:
        exclude:
          - tag
  - commands:
      - make check-license
      - make generate
      - git diff --exit-code
    environment:
      CGO_ENABLED: '0'
      GO111MODULE: 'on'
    image: golang:latest
    name: generate
    pull: always
    when:
      event:
        exclude:
          - tag
