---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: golang:1.12
  commands:
  - make build
  - make test
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: generate
  pull: always
  image: golang:1.12
  commands:
  - make check-license
  - make generate
  - git diff --exit-code
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

...
