---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: gomod
  pull: always
  image: golang:latest
  commands:
  - go mod vendor
  - git diff --exit-code
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-1.11
  pull: always
  image: golang:1.11
  commands:
  - make build
  - make test
  - make test-integration
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-1.12
  pull: always
  image: golang:1.12
  commands:
  - make build
  - make test
  - make test-integration
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-1.13
  pull: always
  image: golang:1.13
  commands:
  - make build
  - make test
  - make test-integration
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: build-1.14
  pull: always
  image: golang:1.14
  commands:
  - make build
  - make test
  - make test-integration
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: generate
  pull: always
  image: golang:latest
  commands:
  - make check-license
  - make generate
  - git diff --exit-code
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
      exclude:
      - tag

- name: goreleaser
  pull: always
  image: golang:1.14
  commands:
  - curl -sL https://git.io/goreleaser | bash
  environment:
    CGO_ENABLED: 0
    GITHUB_TOKEN:
      from_secret: github_token
    GO111MODULE: on
  when:
    event:
    - tag

- name: docker
  pull: always
  image: plugins/docker
  settings:
    auto_tag: true
    password:
      from_secret: docker_password
    repo: jsonnet/bundler
    username:
      from_secret: docker_username
  when:
    event:
    - tag

...
