archives:
  - builds:
      - jb
    format: binary
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}'
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - binary: jb
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    goos:
      - darwin
      - linux
      - windows
    id: jb
    ldflags:
      - -s -w -extldflags "-static" -X main.Version={{.Version}}
    main: ./cmd/jb
dist: _output
dockers:
  - builds:
      - jb
    goarch: amd64
    goos: linux
    image_templates:
      - jsonnet/bundler:latest
      - jsonnet/bundler:v{{ .Major }}
      - jsonnet/bundler:v{{ .Major }}.{{ .Minor }}
      - jsonnet/bundler:{{ .Tag }}
    skip_push: false
project_name: jb
release:
  draft: true
  github:
    name: jsonnet-bundler
    owner: jsonnet-bundler
